# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 600)
        MainWindow.setMinimumSize(QtCore.QSize(730, 600))
        MainWindow.setMaximumSize(QtCore.QSize(730, 600))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #283655;\n"
"    color: #c4dfe6;\n"
"    font-family: \"Bahnschrift SemiBold\";\n"
"}\n"
"QLabel {\n"
"    color: #c4dfe6;\n"
"    font-family: \"Verdana\";\n"
"    font-size: 16pt;\n"
"}\n"
"QPushButton{\n"
"    color: #c4dfe6;\n"
"    border: 2px solid #1e1f26;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    background-color: #4d648d;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #d0e1f9;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #d0e1f9;\n"
"    border: 5px solid #1e1f26;\n"
"}\n"
"QLineEdit{\n"
"    color: #c4dfe6;\n"
"    background-color: #d0e1f9;\n"
"    font-size: 20;\n"
"    border: 2px solid #1e1f26;\n"
"    border-radius: 3px;\n"
"}\n"
"QTableWidget {\n"
"    background-color:  #121212;\n"
"    color: #c4dfe6;\n"
"    font-family: \"Bahnschrift SemiBold\";\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #673AB7;\n"
"    color: #c4dfe6;\n"
"    padding: 4px;\n"
"    border: 1px solid #5E35B1;\n"
"    font-weight: bold;\n"
"}\n"
"Line{\n"
"    color: #c4dfe6;\n"
"}")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Ukrainian, QtCore.QLocale.Country.Ukraine))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QMainWindow {\n"
"    background-color: #283655;\n"
"    color: #d0e1f9;\n"
"    font-family: \"Bahnschrift SemiBold\";\n"
"}\n"
"QLabel {\n"
"    color: #d0e1f9;\n"
"    font-family: \"ahnschrift SemiBold\";\n"
"    font-size: 16pt;\n"
"}\n"
"QPushButton{\n"
"    color: #d0e1f9;\n"
"    border: 1px solid #1e1f26;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    background-color: #4d648d;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #d0e1f9;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #d0e1f9;\n"
"    border: 3px solid #1e1f26;\n"
"}\n"
"QLineEdit{\n"
"    color: #1e1f26;\n"
"    background-color: #d0e1f9;\n"
"    font-size: 20;\n"
"    border: 1px solid #1e1f26;\n"
"    border-radius: 5px;\n"
"}\n"
"QTableWidget {\n"
"    background-color:  #283655;\n"
"    border: 1px solid #1e1f26;\n"
"    color: #d0e1f9;\n"
"    font-family: \"Bahnschrift SemiBold\";\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #283655;\n"
"    color: #d0e1f9;\n"
"    font-weight: bold;\n"
"}\n"
"Line{\n"
"    color: #c4dfe6;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_naming = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_naming.sizePolicy().hasHeightForWidth())
        self.lbl_naming.setSizePolicy(sizePolicy)
        self.lbl_naming.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(-1)
        self.lbl_naming.setFont(font)
        self.lbl_naming.setStyleSheet("QLabel{\n"
"    font-family: \"Bahnschrift SemiBold\";\n"
"    font-size: 30px;\n"
"}")
        self.lbl_naming.setObjectName("lbl_naming")
        self.verticalLayout.addWidget(self.lbl_naming, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 25))
        self.line.setMaximumSize(QtCore.QSize(712, 3))
        self.line.setStyleSheet("Line{\n"
"    margin: 10px;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_add.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.line_add = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_add.sizePolicy().hasHeightForWidth())
        self.line_add.setSizePolicy(sizePolicy)
        self.line_add.setMinimumSize(QtCore.QSize(0, 30))
        self.line_add.setObjectName("line_add")
        self.horizontalLayout.addWidget(self.line_add)
        self.btn_left = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_left.sizePolicy().hasHeightForWidth())
        self.btn_left.setSizePolicy(sizePolicy)
        self.btn_left.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_left.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_left.setObjectName("btn_left")
        self.horizontalLayout.addWidget(self.btn_left)
        self.scroll_nums = QtWidgets.QScrollArea(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_nums.sizePolicy().hasHeightForWidth())
        self.scroll_nums.setSizePolicy(sizePolicy)
        self.scroll_nums.setMinimumSize(QtCore.QSize(0, 0))
        self.scroll_nums.setMaximumSize(QtCore.QSize(16777215, 30))
        self.scroll_nums.setStyleSheet("QScrollArea {\n"
"    background-color: #283655;\n"
"    border: 1px solid #1e1f26;\n"
"    border-radius: 5px;\n"
"}")
        self.scroll_nums.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll_nums.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll_nums.setWidgetResizable(True)
        self.scroll_nums.setObjectName("scroll_nums")
        self.scroll_content = QtWidgets.QWidget()
        self.scroll_content.setGeometry(QtCore.QRect(0, 0, 16, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_content.sizePolicy().hasHeightForWidth())
        self.scroll_content.setSizePolicy(sizePolicy)
        self.scroll_content.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"}")
        self.scroll_content.setObjectName("scroll_content")
        self.scroll_nums.setWidget(self.scroll_content)
        self.horizontalLayout.addWidget(self.scroll_nums, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.btn_right = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_right.sizePolicy().hasHeightForWidth())
        self.btn_right.setSizePolicy(sizePolicy)
        self.btn_right.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_right.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_right.setObjectName("btn_right")
        self.horizontalLayout.addWidget(self.btn_right)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.table_prob = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_prob.sizePolicy().hasHeightForWidth())
        self.table_prob.setSizePolicy(sizePolicy)
        self.table_prob.setStyleSheet("QHeaderView::section {\n"
"    border: none;\n"
"    background-color: #283655;\n"
"    gridline-color: #1e1f26;\n"
"    color: #d0e1f9;\n"
"    font-weight: bold;\n"
"}")
        self.table_prob.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.table_prob.setObjectName("table_prob")
        self.table_prob.setColumnCount(4)
        self.table_prob.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_prob.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prob.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prob.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_prob.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.table_prob)
        self.table_stats = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_stats.sizePolicy().hasHeightForWidth())
        self.table_stats.setSizePolicy(sizePolicy)
        self.table_stats.setMinimumSize(QtCore.QSize(303, 0))
        self.table_stats.setStyleSheet("QHeaderView::section {\n"
"    border: none;\n"
"    background-color: #283655;\n"
"    gridline-color: #1e1f26;\n"
"    color: #d0e1f9;\n"
"    font-weight: bold;\n"
"}")
        self.table_stats.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.table_stats.setObjectName("table_stats")
        self.table_stats.setColumnCount(3)
        self.table_stats.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_stats.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_3.addWidget(self.table_stats)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.new_game = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_game.sizePolicy().hasHeightForWidth())
        self.new_game.setSizePolicy(sizePolicy)
        self.new_game.setMinimumSize(QtCore.QSize(100, 30))
        self.new_game.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.new_game.setCheckable(True)
        self.new_game.setObjectName("new_game")
        self.horizontalLayout_4.addWidget(self.new_game)
        self.save_game = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_game.sizePolicy().hasHeightForWidth())
        self.save_game.setSizePolicy(sizePolicy)
        self.save_game.setMinimumSize(QtCore.QSize(100, 30))
        self.save_game.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.save_game.setCheckable(True)
        self.save_game.setObjectName("save_game")
        self.horizontalLayout_4.addWidget(self.save_game)
        self.load_game = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_game.sizePolicy().hasHeightForWidth())
        self.load_game.setSizePolicy(sizePolicy)
        self.load_game.setMinimumSize(QtCore.QSize(100, 30))
        self.load_game.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.load_game.setCheckable(True)
        self.load_game.setObjectName("load_game")
        self.horizontalLayout_4.addWidget(self.load_game)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Аналіз Колеса Фортуни"))
        self.lbl_naming.setText(_translate("MainWindow", "Аналіз Колеса Фортуни"))
        self.btn_add.setText(_translate("MainWindow", "Додати"))
        self.btn_left.setText(_translate("MainWindow", "←"))
        self.btn_right.setText(_translate("MainWindow", "→"))
        item = self.table_prob.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Категорія"))
        item = self.table_prob.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значення"))
        item = self.table_prob.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Імовірність"))
        item = self.table_prob.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Ставка"))
        item = self.table_stats.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Категорія"))
        item = self.table_stats.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значення"))
        item = self.table_stats.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Кількість"))
        self.new_game.setText(_translate("MainWindow", "Нова Гра"))
        self.save_game.setText(_translate("MainWindow", "Зберегти"))
        self.load_game.setText(_translate("MainWindow", "Завантажити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
